<<<<<<< HEAD
name: RestriÃ§Ã£o de PRs para main
=======
name: Verificar origem do PR para main
>>>>>>> develop

on:
  pull_request:
    branches:
      - main

jobs:
<<<<<<< HEAD
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar origem do PR
        run: |
          BASE_BRANCH="${{ github.base_ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"
          echo "Base: $BASE_BRANCH"
          echo "Head: $HEAD_BRANCH"
          
          if [[ "$BASE_BRANCH" == "main" && ! "$HEAD_BRANCH" =~ ^(develop|hotfix/.*)$ ]]; then
            echo "ðŸš¨ Pull Requests para 'main' sÃ³ sÃ£o permitidos a partir de 'develop' ou 'hotfix/*'."
            exit 1
          else
            echo "âœ… PR com origem vÃ¡lida."
=======
  check-pr-origin:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando se PR veio de develop ou hotfix/*
        run: |
          BASE_BRANCH="${{ github.base_ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"
          echo "Base branch: $BASE_BRANCH"
          echo "Head branch: $HEAD_BRANCH"
          if [[ "$BASE_BRANCH" == "main" && ! "$HEAD_BRANCH" =~ ^(develop|hotfix/.*)$ ]]; then
            echo "âŒ PRs para 'main' sÃ³ podem vir de 'develop' ou 'hotfix/*'."
            exit 1
          else
            echo "âœ… Origem vÃ¡lida do PR."
>>>>>>> develop
          fi
